### ISSUE TITLE
Helm configuration->version data type is Integer

### ISSUE THREAD

**Issue by gintautassulskus** [microbean/helm-maven-plugin#28] opened 2018-02-18 16:49 UTC
Hi,

A couple of remarks:

1. At the moment the plugin requires mandatory parameter `<version>` to be of Integer type. 
This makes it infeasible to use project's version `${project.version}` which, in the majority of cases, is not an Integer. 
Would it be possible to change the required type to String?

```
            <plugin>
                <groupId>org.microbean</groupId>
                <artifactId>helm-maven-plugin</artifactId>
                <configuration>
                    <version>1</version>
                    <releaseName>${project.artifactId}</releaseName>
                    <chartUrl>file:${project.basedir}/src/helm</chartUrl>
                </configuration>
            </plugin>
```

2. Helm-maven parameter `<releaseName>` is mandatory whereas for `helm install` it is optional.
3. Seems that the `namespace` parameter is not respected and the project gets deployed to the `default` namespace when I run `helm:install`:
```
            <plugin>
                <groupId>org.microbean</groupId>
                <artifactId>helm-maven-plugin</artifactId>
                <configuration>
                    <version>1</version>
                    <releaseName>${project.artifactId}</releaseName>
                    <chartUrl>file:${project.basedir}/src/helm</chartUrl>
                    <namespace>lalala</namespace>
                </configuration>
            </plugin>
```

**Comment by ljnelson** [comment] 2018-02-19 19:28
Hi; thanks for your input.

Regarding point number one, I can't change `version` to string, because the generated gRPC code accepts only an integer: https://microbean.github.io/microbean-helm/apidocs/hapi/services/tiller/Tiller.GetReleaseStatusRequestOrBuilder.html#getVersion--

Regarding point number two, I'm not sure I understand what you're saying.  Indeed, `releaseName` is an optional parameter for the `install` mojo, just as it is for `helm install`.  That's by design.  There are other mojos for which it is required.  For example, the `status` mojo needs a release name so it knows what release you want a status for: https://microbean.github.io/helm-maven-plugin/status-mojo.html#releaseName

Regarding point number three, there's no `namespace` parameter for the `install` mojo: https://microbean.github.io/helm-maven-plugin/install-mojo.html  You probably want `releaseNamespace`.

**Comment by gintautassulskus** [comment] 2018-02-20 13:22
Thanks for the response. You made the things much clearer to me. I will play with the plugin for the next couple of days. I think my confusion is caused by the lack of general knowledge of how a maven (plugin) configuration works.

The [user guide](https://microbean.github.io/helm-maven-plugin/usage.html) demonstrates how to attach a Helm goal-specific configuration to a specific maven phase. For this, the `configuration` tag is nested within an `execution` tag. Since this is a goal-specific configuration, `releaseName` can be left out for specific operations, e.g. `install`.

I would like to use `helm:*` goals on their own. For that, I configure the plugin outside the `executions` tag. I believe the `configuration` then becomes 'global'. 
For example, the configuration then requires `releaseName` parameter. Presumably, because while the tag is optional for `install`, it is mandatory for `status`.  But when I specify `releaseName` to satisfy the requirement for the `status` goal, then I can no longer 'unset' the value for the `install` goal and let it generate its own release name.

**Comment by ljnelson** [comment] 2018-02-20 16:40
I see.  While a full Maven tutorial is beyond the scope of this issue 😄 I can say that there are certain `helm-maven-plugin` goals that _do_ need a `releaseName` and others that don't.

With Maven plugin configuration, you can, of course, add any element you want (like `<fred>barney</fred>`) and things won't break.  So when you do something like, say, `helm list` (or the [matching goal](https://microbean.github.io/helm-maven-plugin/list-mojo.html)), any `<releaseName>` element is simply ignored.

To do what you're trying to do for all possible `helm-maven-plugin` goals is probably more difficult than simply including the proper Maven plugin configuration in each submodule.  That is, you would have to include enough configuration gunk to supply values for not just the `install` mojo, but the `update`, `list`, `test`, `status`, etc. mojos, and they all take slightly different parameters.

I highly recommend looking at [Maven's guide to configuring plugins](https://maven.apache.org/guides/mini/guide-configuring-plugins.html), bearing in mind that each "verb" in my plugin (in any Maven plugin) is a "mojo", and fundamentally a Java object that gets created and then has its "setters" called on it with values supplied from the XML configuration.  Finally, the documentation for the `helm-maven-plugin` can be found here: https://microbean.github.io/helm-maven-plugin/plugin-info.html  Good luck.

**Comment by gintautassulskus** [comment] 2018-02-20 16:59
Thanks. Well, it just didn't feel 'right' from my maven experience that those few parameters we mandatory in the configuration even though they are required only by a subset of the goals.

**Comment by ljnelson** [comment] 2018-02-20 17:17
They're…not.  That is, they're mandatory for the goals for which they…have to be mandatory.

Let's take an example.  `helm list` doesn't need a release name or a version, because you're listing releases.  Consequently the [list mojo](https://microbean.github.io/helm-maven-plugin/list-mojo.html) doesn't require a release name or a version.

Here's another example.  `helm update` doesn't need a, because you're updating the latest version of a release by definition, but it does need a release name because otherwise how would you know what release to update?  The same things are true of [the update mojo](https://microbean.github.io/helm-maven-plugin/update-mojo.html).

Another one.  `helm install` can't take a version and doesn't need a release name.  If you do supply a release name, that's fine, but otherwise one is generated for you.  The [install mojo](https://microbean.github.io/helm-maven-plugin/install-mojo.html) follows suit.

Do you see how each goal (and matching `helm` command) has a different permitted configuration, and how some of those items are required, and some are not?

To my eyes, only the [content](https://microbean.github.io/helm-maven-plugin/content-mojo.html), [rollback](https://microbean.github.io/helm-maven-plugin/rollback-mojo.html) and [status](https://microbean.github.io/helm-maven-plugin/status-mojo.html) mojos _require_ both a release name and a version (which makes sense, since they need to know specifically what they should be looking at).

**Comment by gintautassulskus** [comment] 2018-02-20 19:36
Thank you, I understand and agree with you that this is the case when the configuration is nested under the `execution` tag as per your [documentation](https://microbean.github.io/helm-maven-plugin/usage.html). The `configuration` is then specific to the specified goal(s).
```
    <plugin>
        <groupId>org.microbean</groupId>
        <artifactId>helm-maven-plugin</artifactId>
        <version>2.7.0.1.0.25</version>
        <executions>
            <execution>
                <phase>package</phase>
                <goals>
                    <goal>status</goal>
                </goals>
                <configuration>
                    <releaseName>mandatory</releaseName>
                    <version>1</version>
                </configuration>
            </execution>
        </executions>
    </plugin>
```

However, I do not want to associate this configuration with a specific goal. I want to be it a 'global' default. For this, I leave out `execution` tags and declare configuration 'just like that':
```
            <plugin>
                <groupId>org.microbean</groupId>
                <artifactId>helm-maven-plugin</artifactId>
                <version>${helm.maven.plugin.version}</version>
                <configuration>
                    <version>1</version>
                    <releaseName>${project.artifactId}</releaseName>
                </configuration>
            </plugin>
```

However, in this use-case `version` and `releaseName` are always mandatory prior knowing what goals are going to be invoked. Please have a look at the root pom.xml of this [demo project](https://github.com/gintautassulskus/demo).

**Comment by ljnelson** [comment] 2018-02-20 20:25
I've cloned your demo project, and one of the other issues you have is that if you invoke a helm-maven-plugin goal from the root level, it will attempt to run the goal from that root level as well.  So if you try to run, say, the install mojo from the root, it will fail before it even starts to process your subprojects.

Here's a snippet showing that:

    mvn org.microbean:helm-maven-plugin:install
    [INFO] Scanning for projects...
    [INFO] ------------------------------------------------------------------------
    [INFO] Detecting the operating system and CPU architecture
    [INFO] ------------------------------------------------------------------------
    [INFO] os.detected.name: osx
    [INFO] os.detected.arch: x86_64
    [INFO] os.detected.version: 10.13
    [INFO] os.detected.version.major: 10
    [INFO] os.detected.version.minor: 13
    [INFO] os.detected.classifier: osx-x86_64
    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Build Order:
    [INFO] 
    [INFO] demo
    [INFO] sub_demo_1
    [INFO] sub_demo_2
    [INFO] sub_demo_3
    [INFO] 
    [INFO] ------------------------------------------------------------------------
    [INFO] Building demo 1.0-SNAPSHOT
    [INFO] ------------------------------------------------------------------------
    [INFO] 
    [INFO] --- helm-maven-plugin:2.7.0.1.0.33:install (default-cli) @ demo ---
    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Summary:
    [INFO] 
    [INFO] demo ............................................... FAILURE [  0.591 s]
    [INFO] sub_demo_1 ......................................... SKIPPED
    [INFO] sub_demo_2 ......................................... SKIPPED
    [INFO] sub_demo_3 ......................................... SKIPPED
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 1.069 s
    [INFO] Finished at: 2018-02-20T12:14:37-08:00
    [INFO] Final Memory: 11M/309M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.microbean:helm-maven-plugin:2.7.0.1.0.33:install (default-cli) on project demo: /Users/LANELSON/Projects/github/gintautassulskus/demo/target/generated-sources/helm/charts/demo (No such file or directory) -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Do you see how the failure here is because there's no `target` directory under `demo` (it doesn't even get to any of the `sub_demo` projects)?

So even if I put in a lenient mode you will still end up running your helm-maven-plugin goal against the parent project, which is almost certainly not what you want.

I also see that you're specifying the plugin version in both `<pluginManagement>` and `<plugins>`, which suggests to me that maybe you aren't fully aware of how `<pluginManagement>` works.  Its primary purpose is to centralize duplicate information.  If you make use of it properly, you could move your `<configuration>` in there and then have actual plugin invocations in your subprojects.  I'll file a pull request against your demo project to show you what I mean.  In short, you're still running up against a Maven misunderstanding more than you're running up against a limitation of the helm-maven-plugin.

Regarding this issue, what I'm going to do is close this bug, open a new enhancement for a silent skip if various source directories don't exist, and leave it at that; I think that plus a good understanding on your part of `<pluginManagement>` will allow you to do whatever you want to do here.

**Comment by ljnelson** [comment] 2018-02-20 20:45
See https://github.com/gintautassulskus/demo/pull/1.

**Closed by ljnelson** 2018-02-20 20:45 UTC
Labels: not a bug
