### ISSUE TITLE
maven package error

### ISSUE THREAD

**Issue by zhoubonet** [microbean/helm-maven-plugin#22] opened 2017-12-14 10:02 UTC
Cannot convert 'file:E:\workspace\test-project\charts\' to URI: Illegal character in opaque part at index 7 error

config demo
<configuration>
                            <chartContentsUri>file:${project.basedir}\charts\</chartContentsUri>
                            <chartTargetUri>file:${project.basedir}\charts\${project.artifactId}.tgz</chartTargetUri>
 </configuration>

**Comment by ljnelson** [comment] 2017-12-15 20:05
Hello; I'm not sure I fully understand what the problem here is.  A URI cannot contain a backslash as a path separator.  From the fragments of configuration you've supplied here, I'm guessing you might have meant:

    <chartContentsUri>file:${project.basedir}/charts</chartContentsUri>

Note the forward slash, `/`, not a backslash, `\`, before `charts`.  Maybe that will help you move forward?

**Comment by ljnelson** [comment] 2017-12-16 20:16
Closing as not a bug.

**Closed by ljnelson** 2017-12-16 20:16 UTC
Labels: not a bug, wontfix

**Comment by zhoubonet** [comment] 2017-12-18 07:26
@ljnelson
use \ ，still error
 Cannot convert 'file:E:\workspace\my-project/charts/' to URI: Illegal character in opaque part at index 7: file:E:\workspace\my-project/charts/ -> [Help 1]

**Comment by zhoubonet** [comment] 2017-12-18 07:34
![image](https://user-images.githubusercontent.com/4209701/34094647-fb0f4660-e408-11e7-998c-45fe8e846f48.png)

**Comment by zhoubonet** [comment] 2017-12-18 09:27
Windows Result
${project.basedir}  get path = file:E:\workspace\my-project/charts/

**Comment by zhoubonet** [comment] 2017-12-18 12:35
my change source is ok
[PackageMojo.zip](https://github.com/microbean/helm-maven-plugin/files/1567891/PackageMojo.zip)

**Comment by ljnelson** [comment] 2017-12-18 16:33
This is still not a bug; I'm sorry.  If you specify a URI, and you use a Maven property that contains backslashes, but you then use forward slashes elsewhere in the URI, then you have not specified a valid URI.

If you really want to specify the URI correctly _and_ use `${project.basedir}` on Windows, then you want to do something like this:

    file:${project.basedir}${file.separator}charts${file.separator}

**Comment by zhoubonet** [comment] 2017-12-19 02:02
OK Thank You

**Comment by zhoubonet** [comment] 2017-12-19 02:56
${file.separator} == \\

Java program is error
URI test=new URI("file:E:\\workspace\\charts\\Chart.yaml");

**Comment by ljnelson** [comment] 2017-12-19 21:55
When you specify a parameter to a Maven plugin, you do so as a string (necessarily).  If the underlying object is one that the Maven plugin configuration system knows how to work with, such as `URI`, then [Maven will try to convert your supplied string into an instance of that type](https://github.com/apache/maven/blob/master/maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java#L607).  This is what is happening here.  helm-maven-plugin does not have any control over how that conversion happens.  I'll look into providing more explicit documentation about how to configure Maven plugins, but this is still not a bug in helm-maven-plugin.
